version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-sistemas
    environment:
      MYSQL_ROOT_PASSWORD: super-secret-password
      MYSQL_DATABASE: election_system
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build: .
    container_name: API-Eleicoes
    ports:
      - "5110:5110"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: election_system
      DB_USERNAME: root
      DB_PASSWORD: super-secret-password
      ASPNETCORE_URLS: http://0.0.0.0:5110

volumes:
  mysql_data:
