version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-election-system
    environment:
      MYSQL_ROOT_PASSWORD: ElectionSystem2024!
      MYSQL_DATABASE: election_system
      MYSQL_USER: election_user
      MYSQL_PASSWORD: ElectionPass2024!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=256M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pElectionSystem2024!"]
      timeout: 30s
      retries: 15
      interval: 5s
    networks:
      - election-network

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: election-api-hybrid
    ports:
      - "5110:5110"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Database Configuration
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: election_system
      DB_USERNAME: root
      DB_PASSWORD: ElectionSystem2024!
      
      # JWT Configuration
      JWT_SECRET_KEY: production-jwt-secret-key-hybrid-photo-system-32-chars-minimum
      JWT_ISSUER: ElectionApi
      JWT_AUDIENCE: ElectionApiUsers
      JWT_EXPIRE_MINUTES: 60
      
      # SMTP Configuration (empty for production)
      SMTP_HOST: 
      SMTP_PORT: 587
      SMTP_ENABLE_SSL: true
      SMTP_USERNAME: 
      SMTP_PASSWORD: 
      SMTP_FROM_EMAIL: 
      SMTP_FROM_NAME: Sistema de Eleições
      
      # Vote Encryption Keys
      VOTE_MASTER_KEY: production-vote-master-key-hybrid-system-32-chars-minimum
      VOTE_JUSTIFICATION_KEY: production-justification-key-hybrid-system-32-chars
      
      # Swagger Configuration
      SWAGGER_USERNAME: admin
      SWAGGER_PASSWORD: HybridSystem2024!
      
      # Environment Settings
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:5110
      
      # Hybrid Photo System Settings
      MAX_PHOTO_SIZE_MB: 10
      PHOTO_QUALITY: 85
      MAX_PHOTO_WIDTH: 800
      MAX_PHOTO_HEIGHT: 600
      
    volumes:
      - photo_uploads:/app/wwwroot/uploads
      - app_logs:/app/logs
    restart: unless-stopped
    networks:
      - election-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5110/health", "||", "exit", "1"]
      timeout: 30s
      retries: 5
      interval: 30s

networks:
  election-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  mysql_config:
    driver: local
  photo_uploads:
    driver: local
  app_logs:
    driver: local
