version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-election-system-v1.2.1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    command: >
      --default-authentication-plugin=mysql_native_password 
      --innodb-buffer-pool-size=256M 
      --max_connections=500
      --innodb-log-file-size=128M
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      timeout: 30s
      retries: 15
      interval: 5s
      start_period: 30s
    networks:
      - election-network
    restart: unless-stopped

  api:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: 1.2.1
    container_name: election-api-v1.2.1
    ports:
      - "5110:5110"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Database Configuration
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      
      # JWT Configuration
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ISSUER: ${JWT_ISSUER:-ElectionApi}
      JWT_AUDIENCE: ${JWT_AUDIENCE:-ElectionApiUsers}
      JWT_EXPIRE_MINUTES: ${JWT_EXPIRE_MINUTES:-60}
      
      # SMTP Configuration
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_ENABLE_SSL: ${SMTP_ENABLE_SSL:-true}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME:-Sistema de Eleições}
      
      # Vote Encryption Keys
      VOTE_MASTER_KEY: ${VOTE_MASTER_KEY}
      VOTE_JUSTIFICATION_KEY: ${VOTE_JUSTIFICATION_KEY}
      
      # Swagger Configuration
      SWAGGER_USERNAME: ${SWAGGER_USERNAME:-admin}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
      
      # Environment Settings
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: http://0.0.0.0:5110
      
      # Hybrid Photo System Settings
      MAX_PHOTO_SIZE_MB: ${MAX_PHOTO_SIZE_MB:-10}
      PHOTO_QUALITY: ${PHOTO_QUALITY:-85}
      MAX_PHOTO_WIDTH: ${MAX_PHOTO_WIDTH:-800}
      MAX_PHOTO_HEIGHT: ${MAX_PHOTO_HEIGHT:-600}
      
      # System Seal Configuration
      SYSTEM_SEAL_SECRET: ${SYSTEM_SEAL_SECRET:-system-seal-secret-key-production}
      
      
      # API Features
      ENABLE_SWAGGER: ${ENABLE_SWAGGER:-true}
      API_VERSION: 1.2.1
      API_BUILD_DATE: "2025-08-05"
      
    volumes:
      - photo_uploads:/app/wwwroot/uploads
      - app_logs:/app/logs
    restart: unless-stopped
    networks:
      - election-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5110/health", "||", "exit", "1"]
      timeout: 30s
      retries: 5
      interval: 30s

networks:
  election-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  mysql_config:
    driver: local
  photo_uploads:
    driver: local
  app_logs:
    driver: local
